---
kind: pipeline
name: build
steps:
- name: clone theme
  image: &image_git plugins/git
  commands:
  - git config user.name "Suzuki Shunsuke"
  - git config user.email "suzuki.shunsuke.1989@gmail.com"
  - git clone --depth 1 https://github.com/suzuki-shunsuke/hugo_theme_beg themes/beg
- name: hugo
  image: suzukishunsuke/hugo-ci:0.2.1
  commands:
  - hugo
- name: release
  image: *image_git
  commands:
  - git fetch
  - mkdir ~/.ssh
  - chmod -R 700 ~/.ssh
  - cp ssh_config ~/.ssh/config 
  - cp README.md public
  - git checkout -b master origin/master
  - mv .git CNAME public
  - cd public
  - git status --porcelain
  - git add .
  - git commit -m "update"
  - chmod -R 700 ~/.ssh
  - test -n "$${DEPLOY_KEY}" || exit 1
  - echo "$${DEPLOY_KEY}" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - git push git@github.com:suzuki-shunsuke/suzuki-shunsuke.github.io master
  environment:
    DEPLOY_KEY:
      from_secret: deploy_key
