# baseURL = "https://techblog.szksh.cloud/"
baseURL = "https://techblog-szksh-cloud.github.io/" 
languageCode = "jp"
title = "melody"
theme = "beg"

[taxonomies]
  tag = "tags"
  archive = "archives"
