name: pull request
on: pull_request
permissions: {}
concurrency:
  group: ${{ github.workflow }}--${{ github.ref }}
  cancel-in-progress: true
jobs:
  path-filter:
    # Get changed files to filter jobs
    outputs:
      renovate-config-validator: ${{steps.changes.outputs.renovate-config-validator}}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    timeout-minutes: 15
    steps:
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          filters: |
            renovate-config-validator:
              - renovate.json5
              - .github/workflows/pull_request.yaml
              - .github/workflows/workflow_call_renovate-config-validator.yaml
            update-aqua-checksums:
              - aqua.yaml
              - aqua-checksums.yaml
              - .github/workflows/workflow_call_update-aqua-checksums.yaml

  status-check:
    # This job is used for main branch's branch protection rule's status check.
    # If all dependent jobs succeed or are skipped this job succeeds.
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - renovate-config-validator
      - test
    permissions: {}
    if: failure()
    steps:
      - run: exit 1

  renovate-config-validator:
    uses: ./.github/workflows/workflow_call_renovate-config-validator.yaml
    needs: path-filter
    permissions:
      contents: read

  update-aqua-checksums:
    uses: ./.github/workflows/workflow_call_update-aqua-checksums.yaml
    needs: path-filter
    permissions:
      contents: read
    secrets:
      gh_app_id: ${{secrets.APP_ID}}
      gh_app_private_key: ${{secrets.APP_PRIVATE_KEY}}

  test:
    uses: ./.github/workflows/workflow_call_release.yaml
    with:
      is_release: false
