name: Release
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get nested property
        id: package_json
        uses: notiz-dev/github-action-json-property@a5a9c668b16513c737c3e1f8956772c99c73f6e8 # v0.2.0
        with: 
          path: package.json
          prop_path: volta.node
      - uses: actions/setup-node@v3
        with:
          node-version: ${{steps.package_json.outputs.prop}}
          cache: 'yarn'
      - run: yarn install
      - run: yarn build
      - run: echo "techblog.szksh.cloud" > build/CNAME
      - uses: peaceiris/actions-gh-pages@v3
        if: github.event_name != 'pull_request'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          destination_dir: ./docs
